### ISSUE TITLE
Design UI

### ISSUE THREAD

**Issue by psywombats** [psywombats/7drl2015#1]
We need to have some sort of ability bar or whatever to indicate to the player what skills they can use. Think TOME, RS, Diablo, etc. Max we need to support is probably ~10 abilities. It'd be great to get a nice-looking version of this, but a programmer-art one will suffice for now. For screen size I'm thinking 960*720.

For the icons themselves, could use this: http://game-icons.net/
But more probably we'll just reuse the icon of the granting item as the skill icon.

**Comment by crumley** [comment]
You've got the wrong github account.
