### ISSUE TITLE
Decide on tile resolution

### ISSUE THREAD

**Issue by psywombats** [psywombats/7drl2015#2]
@crumley467 @phil-mansfield This is kind of super important to figure out now before any graphics stuff starts.

Possible choices:
16x16 game, 16x16 display
16x16 game, 32x32 display
32x32 game, 32x32 display

The sizes of random assets we have right now:
16x16: RMN-designed tilesets, Golden Age tilesets, Golden Age charsets, RMN charsets
32x32: ZSII tilesets, scaled Golden Age charsets from ZSII

ZSII uses 32x32 game, 32x32 display resolution with true 32x32 tiles and 16x16 charsets that are manually scaled up via the Scale2x pixel scaling algorithm.

My thoughts: it'd be easy to make new tiles and items at 16x16 and we already have lots of enemies at 16x16. However, all the ZSII tiles are 32x32, and the ZSII map generation algorithms use a lot of decorators that are specific to those 32x32 tiles. We can change to 16x16, but our maps will look a lot blander. I'm going to make an experimental branch to see how it works and then would like feedback.

**Comment by psywombats** [comment]
Branch is no_decorators. Looks alright. Would be nice to fit maps on the screen without scrolling.

**Comment by crumley467** [comment]
The no scrolling is a very strong case for using the 16x16 tilesets

**Comment by psywombats** [comment]
I'm actually going to say that we're going with 32x32 because it will take a non-trivial amount of time to adjust the tile data and map generation algorithms to use new 16x16 tiles.

**Comment by crumley467** [comment]
very well. This will make my step one on resources be blowing up all of the files to the correct size
