### ISSUE TITLE
Playtesting!!

### ISSUE THREAD

**Issue by psywombats** [psywombats/7drl2015#23]
The game is playable now, @phil-mansfield @crumley467 , time to get some coverage. Feel free to add tickets with bugs and balance issues, I've started spamming up the backlog already.

**Comment by crumley467** [comment]
Can do!!
Well that is for the next couple hours before i have to go back to school...

**Comment by crumley467** [comment]
Game doesnt run directly from the executable....

**Comment by psywombats** [comment]
we have an executable?
