### ISSUE TITLE
Find/create item images

### ISSUE THREAD

**Issue by psywombats** [psywombats/7drl2015#3]
This will serve as an ongoing ticket for items that need images. We'll have to wait on https://github.com/psywombats/7drl2015/issues/2 before doing any of this, unfortunately.

Possible resources:
- The existing Golden Age item images, they're 16x16 and can be scaled to 32x32 via Scale2x
- Radiant Dawn http://www.spriters-resource.com/resources/sheets/49/51813.png (22x22)
- FFTA https://dl.dropboxusercontent.com/u/8176126/ffta_items.zip (16x16)
  others?
- Sacred Stones http://serenesforest.net/the-sacred-stones/ (under Inventory) (16x16)

Not sure which set would work best. Fire Emblems have spellbooks but no armor, FFTA has armor but no spellbooks. Golden Age has a mishmash of stuff.

Items we'll definitely need:
- Boots
- Ring
- Spellbook (possibly many of these?)

Need these as well, and possibly in two versions for shitty/good:
- Knife
- Axe
- Mace
- Spear
- Sword
- Rapier
- Bow
- Small shield
- Tower shield
- Robes
- Light armor
- Heavy armor

Probably need these:
- Helmet
- Gloves
- Belt?
- Misc crappy armor?

**Comment by crumley467** [comment]
Got 3x of each of the things requested other than the belts, but that was a longshot

**Comment by psywombats** [comment]
Just need light armor I think? rest is looking good

**Comment by psywombats** [comment]
n/m I'm an idiot
