### ISSUE TITLE
Implement/create visually distinct sprites for mage/soldier/lord enemies

### ISSUE THREAD

**Issue by crumley467** [psywombats/7drl2015#9]
I've started the ball rolling on this one, I'll upload the results in a minute. Figuring out how to do this with nonhumanoid monsters is gonna be a bit of a pain, but I'll work on it.

**Comment by psywombats** [comment]
Push these when you get a chance.

**Comment by psywombats** [comment]
Overlays are implemented. I've also sprited out a few mini-weapons. If you can do more in this style it'd be great.

**Comment by psywombats** [comment]
did it myself
